/* Swara: static, offline-capable UI. No audio, microphone, or network requests. */
(() => {
  'use strict';
  const data=window.SWARA_DATA,core=window.SwaraCore,main=document.getElementById('main');
  core.validate(data);
  const KEY='swara.website.preferences.v1', emptyFilters=()=>({deities:[],raga:[],taal:[],language:[],composer:[],script:[]});
  const defaults={song:'apani-karile',size:'normal',seconds:6,rate:1,motion:false,next:false,mode:'pace'};
  let prefs={...defaults};
  try { const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){
    if(data.songs.some(s=>s.id===saved.song))prefs.song=saved.song;
    if(['normal','compact'].includes(saved.size))prefs.size=saved.size;
    if(Number.isFinite(saved.seconds)&&saved.seconds>=.5&&saved.seconds<=15)prefs.seconds=saved.seconds;
    if([1,2,4].includes(saved.rate))prefs.rate=saved.rate;
    if(['pace','manual'].includes(saved.mode))prefs.mode=saved.mode;
    if(typeof saved.motion==='boolean')prefs.motion=saved.motion;
    if(typeof saved.next==='boolean')prefs.next=saved.next;
  }}catch{}
  if(matchMedia('(prefers-reduced-motion: reduce)').matches)prefs.motion=false;
  const state={query:'',filters:emptyFilters(),view:'songs',passage:0,elapsed:0,column:-1,running:false,timer:0,readScroll:{}};
  let wakeLock=null,resizeTimer=null,toastTimer=null;
  const q=(selector)=>main.querySelector(selector),song=()=>data.songs.find(s=>s.id===prefs.song);
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icons={play:'<path d="m7 4 13 8-13 8z"/>',pause:'<path d="M8 4v16M16 4v16"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',chevron:'<path d="m6 9 6 6 6-6"/>',back:'<path d="m14 6-6 6 6 6"/>',next:'<path d="m10 6 6 6-6 6"/>',expand:'<path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5"/>'};
  const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.play}</svg>`;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(prefs));}catch{}}
  function toast(text){const el=document.getElementById('toast');clearTimeout(toastTimer);el.textContent=text;el.hidden=false;toastTimer=setTimeout(()=>el.hidden=true,4000);}
  function note(text){if(!text.startsWith('_'))return escape(text);const [low,rest='']=text.slice(1).split('~');return `<u>${escape(low)}</u>${escape(rest)}`;}
  function results(){return data.songs.filter(s=>core.matches(s,state.query,state.filters));}
  const fields=[['deities','Deity'],['raga','Raga'],['taal','Taal'],['language','Language'],['composer','Poet / composer'],['script','Script']];
  function filterValues(key){return key==='deities'?data.deities:[...new Set(data.songs.flatMap(s=>core.values(s,key)))].sort();}
  function optionCount(key,value){const f={...state.filters,[key]:[value]};return data.songs.filter(s=>core.matches(s,state.query,f)).length;}
  function renderFilters(){const open=q('.facet[open]')?.dataset.key;const active=document.activeElement?.dataset.value;
    q('#filters').innerHTML=fields.map(([key,label])=>`<details class="facet ${state.filters[key].length?'has-value':''}" data-key="${key}" ${open===key?'open':''}><summary>${label}${state.filters[key].length?' · '+state.filters[key].length:''}${icon('chevron')}</summary><div class="facet-panel" role="group" aria-label="${label}">${filterValues(key).map(value=>`<label class="facet-option"><input type="checkbox" data-filter="${key}" data-value="${escape(value)}" ${state.filters[key].includes(value)?'checked':''}><span>${escape(value)}</span><small>${optionCount(key,value)}</small></label>`).join('')}<button class="facet-close" data-action="close-filter">Done</button></div></details>`).join('');
    q('#applied').innerHTML=fields.flatMap(([key,label])=>state.filters[key].map(value=>`<button class="chip" data-action="remove-filter" data-key="${key}" data-value="${escape(value)}" aria-label="Remove ${label} ${escape(value)} filter">${escape(value)} ×</button>`)).join('');
    const count=Object.values(state.filters).reduce((n,values)=>n+values.length,0);q('#clear-filters').hidden=!count;
    if(open&&active){const input=[...main.querySelectorAll('[data-filter]')].find(el=>el.dataset.filter===open&&el.dataset.value===active);input?.focus({preventScroll:true});}
  }
  function renderResults(){const found=results();q('#result-count').textContent=`${found.length} ${found.length===1?'song':'songs'}${state.query?' matching “'+state.query+'”':''}`;
    q('#songs-list').innerHTML=found.length?found.map(s=>`<article class="song-row"><button class="song-title-button" data-action="read-song" data-song="${s.id}"><strong lang="hi">${escape(s.title)}</strong><span>${escape(s.roman)}</span><span class="song-tags">${escape(s.raga)} · ${escape(s.taal)} · ${escape(s.language)}</span></button><div class="song-meta">${escape(s.raga)}<small>Raga</small></div><div class="song-meta">${escape(s.taal)}<small>${s.beatsPerCycle} beats</small></div><div class="song-meta author">${escape(s.composer||'Not specified')}<small>Poet / composer</small></div><button class="icon-button" data-action="play-song" data-song="${s.id}" aria-label="Play ${escape(s.roman)}">${icon('play')}</button></article>`).join(''):`<div class="empty-state"><h2>No songs match these filters</h2><p>Try another deity, raga, taal, or search term.</p><button class="button" data-action="reset-search">Clear search & filters</button></div>`;
    q('#search-clear').hidden=!state.query;
  }
  function renderSongs(){main.innerHTML=`<section aria-labelledby="page-title"><div class="page-top"><div><p class="eyebrow">Your collection</p><h1 id="page-title">Songs for your harmonium</h1><p class="subtle">Choose a song to read or follow as you sing.</p></div><span class="count-badge">3 complete scores</span></div><div class="search-wrap"><label for="song-search" class="sr-only">Search song titles, lyrics, or metadata</label>${icon('search')}<input class="search-input" id="song-search" type="search" placeholder="Search songs, lyrics, raga…" value="${escape(state.query)}" autocomplete="off"><button id="search-clear" class="search-clear" data-action="clear-search" aria-label="Clear search" ${state.query?'':'hidden'}>×</button></div><p class="search-caption">Search in English or the song’s script. Try “Adya Shakti”, “Iman” or “puja”.</p><div class="filter-bar" id="filters"></div><div class="applied" id="applied"></div><div class="results-meta"><span id="result-count" role="status" aria-live="polite"></span><button class="button quiet" id="clear-filters" data-action="clear-filters" hidden>Clear filters</button></div><div class="song-head" aria-hidden="true"><span>Song</span><span>Raga</span><span>Taal</span><span class="author">Poet / composer</span><span>Play</span></div><div id="songs-list"></div></section>`;renderFilters();renderResults();}
  function facts(s){return `<div class="song-facts"><span><b>Raga</b> ${escape(s.raga)}</span><span><b>Taal</b> ${escape(s.taal)}</span>${s.composer?`<span>${escape(s.composer)}</span>`:''}<span>${escape(s.language)} · ${escape(s.script)}</span></div>`;}
  function blockHTML(s,block,index,width,size='normal',hideHeader=false){const minCell=size==='compact'?44:48,chunks=core.packGroups(s.groups,Math.max(150,width-34),minCell);return `<section class="score-block" aria-label="Notation passage ${index+1}">${hideHeader?'':`<div class="block-label"><span class="block-index">${String(index+1).padStart(2,'0')}</span><span>${s.groups.reduce((a,b)=>a+b,0)} positions</span></div>`}${chunks.map((chunk,ci)=>`${ci?`<div class="continuation">Continued · positions ${chunk[0].start+1}–${chunk.at(-1).start+chunk.at(-1).count}</div>`:''}<div class="score-line">${chunk.map(group=>`<div class="score-group" style="flex:${group.count}"><table class="score-table"><caption class="sr-only">Group ${group.index+1}, positions ${group.start+1} to ${group.start+group.count}. Swaras above corresponding lyrics.</caption><thead><tr>${Array.from({length:group.count},(_,i)=>`<th scope="col">${group.start+i+1}${i===0?`<b>${s.marks[group.index]}</b>`:''}</th>`).join('')}</tr></thead><tbody>${block.rows.filter(r=>r.cells.slice(chunk[0].start,chunk.at(-1).start+chunk.at(-1).count).some(c=>c.text)).map(r=>`<tr>${r.cells.slice(group.start,group.start+group.count).map((c,i)=>`<td class="${c.kind}" data-column="${group.start+i}" lang="hi">${c.kind==='swara'?note(c.text):escape(c.text)||'&nbsp;'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`).join('')}</div>`).join('')}</section>`;}
  function renderNotation(){if(state.view==='read'){const el=q('#full-score');if(!el)return;const s=song(),width=el.clientWidth;el.innerHTML=s.blocks.map((b,i)=>blockHTML(s,b,i,width,prefs.size)).join('');}else if(state.view==='play')renderPassage();}
  function renderRead(){const s=song();main.innerHTML=`<section aria-labelledby="page-title"><div class="page-top"><div class="reader-title"><p class="eyebrow">Read</p><h1 id="page-title" lang="hi">${escape(s.title)}</h1><p class="reader-roman">${escape(s.roman)}</p>${facts(s)}</div><div class="reader-actions"><label class="size-label" for="notation-size">Notation size<select id="notation-size"><option value="normal" ${prefs.size==='normal'?'selected':''}>Normal</option><option value="compact" ${prefs.size==='compact'?'selected':''}>Compact</option></select></label><button class="button primary" data-action="open-player">${icon('play')} Play</button></div></div><div class="notation-toolbar"><div class="legend"><span class="swaras">Swaras</span><span class="lyrics">Lyrics</span></div><span class="group-info">Groups ${s.groups.join(' + ')} · × sam · 0 khali</span><a class="sheet-link" href="${escape(s.source)}" target="_blank" rel="noopener">Published source ↗</a></div><div id="full-score" class="score" data-size="${prefs.size}"></div><p class="score-end">End of song</p><details class="reader-note"><summary>About this transcription</summary><p>All notation rows from the supplied screenshot are included, with repeated lyric lines and blank cells retained. This is a screenshot transcription; review fine musical marks against the original Excel before using it as an authoritative score. Published source opens Svarakusumanjali, the Ramakrishna Math and Ramakrishna Mission publication these songs are drawn from; it is the collection, not a per-song facsimile. Deity labels are collection tags.</p></details></section>`;renderNotation();}
  function renderPlay(){const s=song();main.innerHTML=`<section class="player-view" aria-labelledby="page-title"><div class="page-top"><div><p class="eyebrow">Play · harmonium view</p><h1 id="page-title" class="player-title" lang="hi">${escape(s.title)}</h1><p class="subtle">${escape(s.raga)} · ${escape(s.taal)} <span id="passage-count"></span></p></div><div class="player-controls-top"><label class="sr-only" for="follow-mode">Following mode</label><select class="mode-select" id="follow-mode"><option value="pace" ${prefs.mode==='pace'?'selected':''}>Pace following</option><option value="manual" ${prefs.mode==='manual'?'selected':''}>Manual</option></select><button class="button" data-action="fullscreen" aria-label="Toggle full screen">${icon('expand')} Full screen</button><a class="button quiet" href="#read">Back to Read</a></div></div><div class="player-stage" id="player-stage"></div><div class="play-progress" role="progressbar" aria-label="Song progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="play-progress-fill"></div></div><div class="transport"><button class="button" id="previous" data-action="previous">${icon('back')} Previous</button><button class="button primary" id="start-pause" data-action="start">${icon('play')} Start</button><button class="button" id="next" data-action="next">Next ${icon('next')}</button></div><p class="player-status" id="player-status" role="status" aria-live="polite">Ready · notation following, no audio playback</p><div class="next-preview" id="next-preview" ${prefs.next?'':'hidden'}><h2>Up next</h2><div id="next-score"></div></div><div class="pace-panel"><div class="pace-field" id="pace-timing" ${prefs.mode==='manual'?'hidden':''}><label for="seconds">Base seconds / phrase <output id="seconds-value">${prefs.seconds}</output></label><input id="seconds" type="range" min="0.5" max="15" step="0.5" value="${prefs.seconds}"></div><div id="pace-rates" ${prefs.mode==='manual'?'hidden':''}><div class="pace-multipliers" role="group" aria-label="Pace multiplier">${[1,2,4].map(rate=>`<button class="button" data-action="rate" data-rate="${rate}" aria-pressed="${prefs.rate===rate}">${rate}×</button>`).join('')}</div><div class="effective" id="effective"></div></div><div class="toggles"><label><input id="next-toggle" type="checkbox" ${prefs.next?'checked':''}> Next phrase</label><label><input id="motion-toggle" type="checkbox" ${prefs.motion?'checked':''}> Light motion</label></div></div><p class="rotate-hint">Turn your phone sideways for a wider score.</p></section>`;renderPassage();updateTiming();}
  function highlight(force=false){const stage=q('#player-stage');if(!stage)return;const total=song().groups.reduce((a,b)=>a+b,0),column=prefs.mode==='pace'?core.currentColumn(state.elapsed,total):-1;if(!force&&column===state.column)return;state.column=column;stage.querySelectorAll('td.current-cell').forEach(td=>td.classList.remove('current-cell'));if(column<0)return;stage.querySelectorAll(`td[data-column="${column}"]`).forEach(td=>td.classList.add('current-cell'));}
  function renderPassage(animate=false){const s=song(),stage=q('#player-stage');if(!stage)return;stage.innerHTML=blockHTML(s,s.blocks[state.passage],state.passage,stage.clientWidth,'normal',true);q('#passage-count').textContent=` · ${state.passage+1} / ${s.blocks.length}`;q('#previous').disabled=state.passage===0;q('#next').disabled=state.passage===s.blocks.length-1;q('#start-pause').disabled=prefs.mode==='manual';q('#next-preview').hidden=!prefs.next||state.passage===s.blocks.length-1;if(prefs.next&&state.passage<s.blocks.length-1){const el=q('#next-score');el.innerHTML=blockHTML(s,s.blocks[state.passage+1],state.passage+1,el.clientWidth,'compact',true);}updateProgress();if(animate&&prefs.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches)stage.animate([{transform:'translateY(6px)'},{transform:'translateY(0)'}],{duration:180,easing:'ease-out'});highlight(true);}
  function updateTiming(){if(!q('#effective'))return;q('#seconds-value').textContent=prefs.seconds;q('#effective').textContent=`Effective: ${Number((prefs.seconds/prefs.rate).toFixed(3))} s / phrase`;}
  function updateProgress(){if(state.view!=='play')return;const value=(state.passage+Math.min(1,state.elapsed))/(song().blocks.length)*100;q('#play-progress-fill').style.width=value+'%';q('.play-progress').setAttribute('aria-valuenow',String(Math.round(value)));}
  async function requestWake(){try{if('wakeLock' in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request('screen');}catch{}}
  function stop(){state.running=false;clearInterval(state.timer);state.timer=0;if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null;}if(q('#start-pause'))q('#start-pause').innerHTML=icon('play')+' Start';}
  function start(){if(prefs.mode==='manual')return;if(state.running){stop();q('#player-status').textContent='Paused · position held';return;}if(state.passage===song().blocks.length-1&&state.elapsed>=1){state.passage=0;state.elapsed=0;renderPassage();}state.running=true;q('#start-pause').innerHTML=icon('pause')+' Pause';q('#player-status').textContent='Following pace';requestWake();let last=performance.now();state.timer=setInterval(()=>{const now=performance.now();state.elapsed+=(now-last)/(prefs.seconds*1000/prefs.rate);last=now;while(state.elapsed>=1){if(state.passage===song().blocks.length-1){state.elapsed=1;stop();updateProgress();q('#player-status').textContent='End of song · Start to replay';return;}state.elapsed-=1;state.passage++;renderPassage(true);}updateProgress();highlight();},30);}
  function openSong(id,view){if(!data.songs.some(s=>s.id===id))throw Error('Unknown song');stop();prefs.song=id;state.passage=0;state.elapsed=0;save();if(location.hash==='#'+view)route();else location.hash=view;}
  function route(){if(state.view==='read')state.readScroll[prefs.song]=window.scrollY;stop();const view=location.hash.replace('#','');state.view=['songs','read','play'].includes(view)?view:'songs';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===state.view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(state.view==='songs')renderSongs();if(state.view==='read')renderRead();if(state.view==='play')renderPlay();document.title=state.view==='songs'?'Swara — Harmonium Songbook':song().roman+' · '+(state.view==='read'?'Read':'Play')+' · Swara';requestAnimationFrame(()=>window.scrollTo({top:state.view==='read'?(state.readScroll[prefs.song]||0):0,behavior:'instant'}));}
  function setFilters(filters){for(const [key,values] of Object.entries(filters)){if(!fields.some(f=>f[0]===key)||!Array.isArray(values)||values.some(v=>!filterValues(key).includes(v)))throw Error('Invalid filter');}Object.assign(state.filters,filters);if(state.view==='songs'){renderFilters();renderResults();}return results().map(s=>({id:s.id,title:s.title}));}
  main.addEventListener('input',event=>{const el=event.target;if(el.id==='song-search'){state.query=el.value;renderResults();renderFilters();}if(el.id==='seconds'){prefs.seconds=Number(el.value);save();updateTiming();}});
  main.addEventListener('change',event=>{const el=event.target;if(el.dataset.filter){const key=el.dataset.filter,value=el.dataset.value;setFilters({[key]:el.checked?[...state.filters[key],value]:state.filters[key].filter(v=>v!==value)});}if(el.id==='notation-size'){prefs.size=el.value;save();q('#full-score').dataset.size=prefs.size;renderNotation();}if(el.id==='next-toggle'){prefs.next=el.checked;save();renderPassage();}if(el.id==='motion-toggle'){prefs.motion=el.checked;save();}if(el.id==='follow-mode'){stop();prefs.mode=el.value;save();q('#pace-timing').hidden=prefs.mode==='manual';q('#pace-rates').hidden=prefs.mode==='manual';q('#player-status').textContent=prefs.mode==='manual'?'Manual · use Previous and Next':'Ready · pace following';renderPassage();}});
  main.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;
    if(action==='read-song'||action==='play-song')openSong(el.dataset.song,action==='read-song'?'read':'play');
    if(action==='open-player')location.hash='play';
    if(action==='clear-search'){state.query='';q('#song-search').value='';renderResults();renderFilters();q('#song-search').focus();}
    if(action==='clear-filters'||action==='reset-search'){state.filters=emptyFilters();if(action==='reset-search'){state.query='';q('#song-search').value='';}renderFilters();renderResults();}
    if(action==='remove-filter')setFilters({[el.dataset.key]:state.filters[el.dataset.key].filter(v=>v!==el.dataset.value)});
    if(action==='close-filter')el.closest('details').open=false;
    if(action==='start')start();
    if(action==='previous'||action==='next'){stop();state.passage=Math.max(0,Math.min(song().blocks.length-1,state.passage+(action==='next'?1:-1)));state.elapsed=0;renderPassage(true);q('#player-status').textContent='Position set manually';}
    if(action==='rate'){prefs.rate=Number(el.dataset.rate);save();main.querySelectorAll('[data-rate]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.rate)===prefs.rate)));updateTiming();}
    if(action==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use your browser’s full-screen option.');}catch{toast('Full screen is unavailable in this browser.');}}
  });
  main.addEventListener('toggle',event=>{if(event.target.matches('.facet')&&event.target.open){main.querySelectorAll('.facet[open]').forEach(d=>{if(d!==event.target)d.open=false;});}},true);
  document.addEventListener('click',event=>{if(!event.target.closest('.facet'))main.querySelectorAll('.facet[open]').forEach(d=>d.open=false);});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')main.querySelectorAll('.facet[open]').forEach(d=>d.open=false);const typing=event.target.matches('input,select,textarea,button,a,summary');if(state.view==='play'&&!typing){if(event.code==='Space'){event.preventDefault();start();}if(event.code==='ArrowRight'&&!q('#next').disabled)q('#next').click();if(event.code==='ArrowLeft'&&!q('#previous').disabled)q('#previous').click();}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running){stop();if(q('#player-status'))q('#player-status').textContent='Paused while this tab was in the background';}});
  document.addEventListener('fullscreenchange',()=>{document.body.classList.toggle('is-fullscreen',!!document.fullscreenElement);renderNotation();});
  window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(renderNotation,120);});
  window.addEventListener('hashchange',route);window.addEventListener('pagehide',stop);route();
  // Feature-detected WebMCP: the same selection and filter functions used by the UI.
  if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
    register({name:'find_songs',title:'Find songs',description:'Search the three song scores by title, lyrics or metadata. Does not change the screen.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input.query!=='string')throw Error('query must be text');return data.songs.filter(s=>core.matches(s,input.query)).map(s=>({id:s.id,title:s.title,raga:s.raga,taal:s.taal}));}});
    register({name:'open_song_for_reading',title:'Open song for reading',description:'Open a song in Read and save it as the last-read song on this device.',inputSchema:{type:'object',properties:{songId:{type:'string'}},required:['songId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||typeof input.songId!=='string')throw Error('songId is required');openSong(input.songId,'read');await new Promise(resolve=>requestAnimationFrame(resolve));return {songId:prefs.song,view:state.view};}});
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
